---
- name: install nginx server
  ansible.builtin.apt:
     name: nginx
     state: present

- name: ensure the server is started
  ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes
     